# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI
on:
  push:
    branches: [master, dev-master]
  pull_request:
    branches: [master, dev-master]

jobs:
  
  Tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: ["10.x"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        if: ${{ github.event == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v2
        if: ${{ github.event != 'pull_request' }}

      - name: Tests on ${{ matrix.os }} - Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn build
      - run: yarn test
        
